trigger:
- master

variables:
  buildPath: $(Build.SourcesDirectory)/build

pool:
  vmImage: 'windows-2019'

steps:
- task: CMake@1
  displayName: CMake - Configure
  inputs:
    cmakeArgs: '-S $(Build.SourcesDirectory) -B $(buildPath) -DBOOST_ROOT=$(BOOST_ROOT_1_72_0)'
    runInsideShell: true

- task: CMake@1
  displayName: CMake - Build
  inputs:
    cmakeArgs: '--build $(buildPath)'
    runInsideShell: true

- task: CopyFiles@2
  displayName: 'Publish - Copy bin'
  inputs:
    SourceFolder: '$(buildPath)'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    
- task: PublishPipelineArtifact@0
  displayName: 'Publish - Artifacts'
  inputs:
    artifactName: 'DebugArtefacts'
    targetPath: '$(Build.ArtifactStagingDirectory)'
